name: Test7
on: workflow_dispatch
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Share keystore with build jobs
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore/clone.keystore
          retention-days: 1
      - name: Share source APK with build jobs
        uses: actions/upload-artifact@v4
        with:
          name: source-apk
          path: Quetta.apk
          retention-days: 1
          compression-level: 0
